# Generated by Django 5.2.9 on 2025-12-13 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Theater',
            new_name='Theatre',
        ),
        migrations.RenameField(
            model_name='screen',
            old_name='theater',
            new_name='theatre',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='price',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='screen',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='seat_type',
        ),
        migrations.RemoveField(
            model_name='show',
            name='show_date',
        ),
        migrations.AddField(
            model_name='seat',
            name='show',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shows.show'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='theatre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shows.theatre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seat',
            name='row',
            field=models.CharField(max_length=5),
        ),
    ]
