# Generated by Django 5.2.9 on 2025-12-14 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_rename_theater_theatre_rename_theater_screen_theatre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='number',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='row',
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_number',
            field=models.CharField(default='A1', max_length=10),
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_type',
            field=models.CharField(choices=[('ELITE', 'Elite'), ('PREMIUM', 'Premium'), ('CLASSIC', 'Classic')], default='CLASSIC', max_length=20),
        ),
        migrations.AlterField(
            model_name='theatre',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
