# Generated by Django 5.2.9 on 2025-12-14 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_remove_seat_number_remove_seat_row_seat_seat_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='seat_number',
        ),
        migrations.AddField(
            model_name='screen',
            name='seats_per_row',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='screen',
            name='total_rows',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='seat',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='seat',
            name='price',
            field=models.IntegerField(default=150),
        ),
        migrations.AddField(
            model_name='seat',
            name='row',
            field=models.CharField(default='A', max_length=2),
        ),
        migrations.AlterField(
            model_name='theatre',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
