# Generated by Django 5.2.9 on 2025-12-14 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_remove_seat_seat_number_screen_seats_per_row_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screen',
            old_name='total_rows',
            new_name='rows',
        ),
        migrations.RemoveField(
            model_name='screen',
            name='seats_per_row',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='seat_type',
        ),
        migrations.AddField(
            model_name='screen',
            name='cols',
            field=models.IntegerField(default=16),
        ),
        migrations.AlterField(
            model_name='seat',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='seat',
            name='row',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='theatre',
            name='location',
            field=models.CharField(default='Chennai', max_length=200),
        ),
    ]
